### PR TITLE
Fix id attributes for RDMO 1.6

### PR DESCRIPTION
**Pull request by jochenklar**
Replaces `project/datacite`, `project/funder`, and `project/partner` with the explicit id attribute in all catalogs (also in `shared`).

There are 5 questionsets in `shared` which use other attributes for collection questionsets:

```
shared/EmiMin/publisso_terms4life_emiminV1_questions.xml
https://rdmorganiser.github.io/terms/questions/emimin/legal-and-ethics/intellectual-property-rights-costs
https://rdmorganiser.github.io/terms/domain/project/costs/ipr

shared/ub_fau_erlangen_nuernberg/dfg-editionen/dfg_editions.xml
https://fdm-bayern.org/eHumanities/questions/DFG_editions_cleansed/allgemeines/other_insitutions
https://rdmorganiser.github.io/terms/domain/project/external_services

shared/ub_fau_erlangen_nuernberg/h2020-ehum/ehum_h2020_fragebogen.xml
https://fdm-bayern.org/eHumanities/questions/Horizon2020/project_details/project_info-PI
https://fdm-bayern.org/eHumanities/domain/H2020/PI

shared/ub_fau_erlangen_nuernberg/dfg-sozkulttheo/dfg_sozkulttheo_fk106.xml
https://fdm-bayern.org/eHumanities/questions/DFG_sozkulttheo/allgemeines/other_insitutions
https://rdmorganiser.github.io/terms/domain/project/external_services

shared/ub_fau_erlangen_nuernberg/dfg-alte-kulturen/dfg_alte_kulturen_fk101.xml
https://fdm-bayern.org/eHumanities/questions/dfg_alte_kulturen_fk101/allgemeines/other_insitutions
https://rdmorganiser.github.io/terms/domain/project/external_services
```

These are deviations from the Attributes in the "official" catalog (which, in principle, is ok). I suggest we keep them as they are.

This PR is on `master`, a rebase of `dev` will be needed when we merge.

### CODE REVIEW

**Review by jmfrenzel — CHANGES_REQUESTED** [review]
Will this change work on instances of rdmo running <v1.6?
If, this is not the case I suggest to cut a release here and add some documentation on compatibility of the data model and catalogs in the readme.

**Comment by jochenklar** [comment]
Yes, you are right, this will not work with RDMO < 1.6 anymore. We could create a release with the old master before merging. Then we document that older users should download the xml files with the release tag.

**Review by jmfrenzel — APPROVED** [review]
Please add also some background on the 'id' attributes into the `</comment>` entry the domain/rdmo.xml . This will point catalogers to the actual usage of that attribute to be used with question sets that are collections. 
 
Technically  looks good. 

Tested only  the rdmo questionnaire in  rdmo v1.6.

**Comment by jochenklar** [comment]
Looking up https://semver.org ... leaving the last `0` is a no-go, so `1.0.0-rdmo-1.6.0` is the way to go.

**Pull request merged**
