### PR TITLE
Content2021mrz

### PR DESCRIPTION
**Pull request by Zack-83**
Hallo zusammen,

in dieser Pull Request werden

- einige zusätzlichen Attribute und Optionen (und eine Bedingung) hinzugefügt
- die Wortfassung an einigen Stellen verbessert
- Änderungen für ein paar formelle Feinheiten vorgeschlagen (Vorsicht!)

Ich bitte alle Beteiligten um ein kritisches Gegenlesen :)

### CODE REVIEW

**Review by jochenklar — APPROVED** [review]

**Comment by Zack-83** [comment]
Hier eine Übersicht aller Änderungsvorschläge:

| Pull Request   | Type                                                | Path                                                            | Old path                                                  |
|----------------|-----------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------|
| Content2021mrz | New condition                                       | embargo                                                         |                                                           |
| Content2021mrz | New condition                                       | existing_data                                                   |                                                           |
| Content2021mrz | New condition                                       | repository_extern                                               |                                                           |
| Content2021mrz | New condition                                       | software_generated                                              |                                                           |
| Content2021mrz | New attribute                                       | project/costs/metadata/list                                     |                                                           |
| Content2021mrz | New attribute                                       | project/costs/preservation/list                                 |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/metadata/vocabularies                           |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/preservation/embargo_why                        |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/preservation/repository_safety                  |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/storage/naming_metadata                         |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/existing_yesno                                  |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/creation_software                               |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/usage_software                                  |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/existing_usage                                  |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/existing_what                                   |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/existing_objectives                             |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/usage_objectives                                |                                                           |
| Content2021mrz | New attribute                                       | project/dataset/existing_origin                                 |                                                           |
| Content2021mrz | New attribute                                       | project/funder/grant_nr                                         |                                                           |
| Content2021mrz | New attribute                                       | project/partner/contact_person/email                            |                                                           |
| Content2021mrz | New attribute                                       | project/partner/repository                                      |                                                           |
| Content2021mrz | New attribute                                       | project/partner/isni                                            |                                                           |
| Content2021mrz | New attribute                                       | project/partner/pic                                             |                                                           |
| Content2021mrz | New attribute                                       | project/research_question/acronym                               |                                                           |
| Content2021mrz | New attribute                                       | project/research_question/objectives                            |                                                           |
| Content2021mrz | New attribute                                       | project/research_question/objectives/objective_relation         |                                                           |
| Content2021mrz | New attribute                                       | project/dmp/dmp_version                                         |                                                           |
| Content2021mrz | New attribute                                       | project/dmp/responsible                                         |                                                           |
| Content2021mrz | Specification of existing attribute                 | project/dataset/format                                          | project/dataset/format                                    |
| Content2021mrz | Rename existing attribute                           | project/dataset/sensitive_data/personal_data                    | project/dataset/sensitive_data/personal_data_yesno        |
| Content2021mrz | Rename existing attribute                           | project/dataset/sensitive_data/personal_data/yesno              | project/dataset/sensitive_data/personal_data_yesno/yesno  |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/responsible_person                 | project/preservation/responsible_person                   |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/responsible_person/name            | project/preservation/responsible_person/name              |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/selection_criteria                 | project/preservation/selection_criteria                   |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/selection_format                   | project/preservation/selection_format                     |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/archive/yesno                      | project/preservation/archive/yesno                        |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/archive/fair_archive               | project/preservation/archive/fair_archive                 |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/archive/nonprofit                  | project/preservation/archive/nonprofit                    |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/archive/nonprofit/yesno            | project/preservation/archive/nonprofit/yesno              |
| Content2021mrz | Change path of existing attribute                   | project/dataset/preservation/archive/nonprofit/explanation      | project/preservation/archive/nonprofit/explanation        |
| Content2021mrz | New optionset                                       | access_permissions/OE                                           |                                                           |
| Content2021mrz | New optionset                                       | access_permissions/partner                                      |                                                           |
| Content2021mrz | New optionset                                       | access_permissions/other                                        |                                                           |
| Content2021mrz | New optionset                                       | access_type/open                                                |                                                           |
| Content2021mrz | New optionset                                       | access_type/embargo                                             |                                                           |
| Content2021mrz | New optionset                                       | access_type/restricted                                          |                                                           |
| Content2021mrz | New optionset                                       | access_type/closed                                              |                                                           |
| Content2021mrz | New optionset                                       | backup_frequency/h                                              |                                                           |
| Content2021mrz | New optionset                                       | backup_frequency/d                                              |                                                           |
| Content2021mrz | New optionset                                       | backup_frequency/w                                              |                                                           |
| Content2021mrz | New optionset                                       | backup_frequency/m                                              |                                                           |
| Content2021mrz | New optionset                                       | backup_frequency/other                                          |                                                           |
| Content2021mrz | New optionset                                       | data_type/DT                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/GR                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/VO                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/AO                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/TT                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/DB                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/GG                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/CD                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/ST                                                    |                                                           |
| Content2021mrz | New optionset                                       | data_type/SO                                                    |                                                           |
| Content2021mrz | New optionset                                       | embargo_why/publication                                         |                                                           |
| Content2021mrz | New optionset                                       | embargo_why/rights                                              |                                                           |
| Content2021mrz | New optionset                                       | embargo_why/other                                               |                                                           |
| Content2021mrz | New optionset                                       | licence/CC-BY                                                   |                                                           |
| Content2021mrz | New optionset                                       | licence/CC-BY-SA                                                |                                                           |
| Content2021mrz | New optionset                                       | licence/other                                                   |                                                           |
| Content2021mrz | New optionset                                       | metadata/identifier                                             |                                                           |
| Content2021mrz | New optionset                                       | metadata/title                                                  |                                                           |
| Content2021mrz | New optionset                                       | metadata/time                                                   |                                                           |
| Content2021mrz | New optionset                                       | metadata/place                                                  |                                                           |
| Content2021mrz | New optionset                                       | metadata/technique                                              |                                                           |
| Content2021mrz | New optionset                                       | metadata/sample                                                 |                                                           |
| Content2021mrz | New optionset                                       | metadata/creator                                                |                                                           |
| Content2021mrz | New optionset                                       | metadata/version_nr                                             |                                                           |
| Content2021mrz | New optionset                                       | metadata/other                                                  |                                                           |
| Content2021mrz | New optionset                                       | objectives/obj1                                                 |                                                           |
| Content2021mrz | New optionset                                       | objectives/obj2                                                 |                                                           |
| Content2021mrz | New optionset                                       | objectives/obj3                                                 |                                                           |
| Content2021mrz | New optionset                                       | objectives/obj4                                                 |                                                           |
| Content2021mrz | New optionset                                       | objectives/obj5                                                 |                                                           |
| Content2021mrz | New optionset                                       | objectives/other                                                |                                                           |
| Content2021mrz | New optionset                                       | preservation_responsible/repository                             |                                                           |
| Content2021mrz | New optionset                                       | preservation_responsible/lib                                    |                                                           |
| Content2021mrz | New optionset                                       | preservation_responsible/calc                                   |                                                           |
| Content2021mrz | New optionset                                       | preservation_responsible/coordinator                            |                                                           |
| Content2021mrz | New optionset                                       | preservation_responsible/datacoord                              |                                                           |
| Content2021mrz | New optionset                                       | preservation_responsible/other                                  |                                                           |
| Content2021mrz | New optionset                                       | purpose/material                                                |                                                           |
| Content2021mrz | New optionset                                       | purpose/constant                                                |                                                           |
| Content2021mrz | New optionset                                       | purpose/phenomenon                                              |                                                           |
| Content2021mrz | New optionset                                       | purpose/other                                                   |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/WDS                                    |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/DSA                                    |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/RatSWD                                 |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/CLARIN                                 |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/TrustSeal                              |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/DINI                                   |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/TRAC                                   |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/DIN31644                               |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/dontknow                               |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/other                                  |                                                           |
| Content2021mrz | New optionset                                       | repository_certification/no                                     |                                                           |
| Content2021mrz | New optionset                                       | security_options/copies                                         |                                                           |
| Content2021mrz | New optionset                                       | security_options/crypto                                         |                                                           |
| Content2021mrz | New optionset                                       | security_options/other                                          |                                                           |
| Content2021mrz | New optionset                                       | sharing/all                                                     |                                                           |
| Content2021mrz | New optionset                                       | sharing/anonym                                                  |                                                           |
| Content2021mrz | New optionset                                       | sharing/partly                                                  |                                                           |
| Content2021mrz | New optionset                                       | sharing/none                                                    |                                                           |
| Content2021mrz | New optionset                                       | storage_support/HD                                              |                                                           |
| Content2021mrz | New optionset                                       | storage_support/USB                                             |                                                           |
| Content2021mrz | New optionset                                       | storage_support/MI                                              |                                                           |
| Content2021mrz | New optionset                                       | storage_support/PPC                                             |                                                           |
| Content2021mrz | New optionset                                       | storage_support/DPC                                             |                                                           |
| Content2021mrz | New optionset                                       | storage_support/OES                                             |                                                           |
| Content2021mrz | New optionset                                       | storage_support/ZS                                              |                                                           |
| Content2021mrz | New optionset                                       | storage_support/PS                                              |                                                           |
| Content2021mrz | New optionset                                       | storage_support/FS                                              |                                                           |
| Content2021mrz | New optionset                                       | storage_support/lab                                             |                                                           |
| Content2021mrz | New optionset                                       | storage_support/SO                                              |                                                           |
| Content2021mrz | New optionset                                       | usage_objectives/obj1                                           |                                                           |
| Content2021mrz | New optionset                                       | usage_objectives/obj2                                           |                                                           |
| Content2021mrz | New optionset                                       | usage_objectives/obj3                                           |                                                           |
| Content2021mrz | New optionset                                       | usage_objectives/obj4                                           |                                                           |
| Content2021mrz | New optionset                                       | usage_objectives/obj5                                           |                                                           |
| Content2021mrz | New optionset                                       | usage_objectives/other                                          |                                                           |
| Content2021mrz | New optionset                                       | usage_software/exist_open                                       |                                                           |
| Content2021mrz | New optionset                                       | usage_software/exist_commercial                                 |                                                           |
| Content2021mrz | New optionset                                       | usage_software/selfgenerated                                    |                                                           |
| Content2021mrz | New optionset                                       | usage_software/other                                            |                                                           |
| Content2021mrz | New optionset                                       | vocabulary/AIP                                                  |                                                           |
| Content2021mrz | New optionset                                       | vocabulary/INSPEC                                               |                                                           |
| Content2021mrz | New optionset                                       | vocabulary/PASCAL                                               |                                                           |
| Content2021mrz | New optionset                                       | vocabulary/MATSCINET                                            |                                                           |
| Content2021mrz | New optionset                                       | vocabulary/other                                                |                                                           |
| Content2021mrz | New single option                                   | dataset_sharing_options/anonym                                  |                                                           |
| Content2021mrz | New single option                                   | preservation_repository_options/138                             |                                                           |
| Content2021mrz | Wording of some options changed                     | dataset_interoperability_options                                |                                                           |
| Content2021mrz | Wording of some options changed                     | dataset_size_options                                            |                                                           |
| Content2021mrz | Wording of some options changed                     | preservation_motivation_options                                 |                                                           |
| Content2021mrz | Wording of some options changed                     | preservation_repository_options                                 |                                                           |
| Content2021mrz | Ordering of options changed                         | …                                                               |                                                           |
| Content2021mrz | New question                                        | rdmo/general/topic-research_field/name                          |                                                           |
| Content2021mrz | Wording of question changed                         | rdmo/general/funding-funder/title                               |                                                           |
| Content2021mrz | Wording of question changed                         | rdmo/technical-classification/data-dates                        |                                                           |
| Content2021mrz | Wording of question changed                         | rdmo/data-usage/quality-assurance-integration/integration       |                                                           |
| Content2021mrz | Link within question changed                        | rdmo/data-usage/data-sharing-and-re-use-publication/conditions  |                                                           |
| Content2021mrz | Minor changes (punctuation, white spaces, newlines) | …                                                               |                                                           |
| Content2021mrz | French & Italian translation                        | …                                                               |                                                           |

**Review by Freund-J — APPROVED** [review]

**Comment by torsten-rathmann** [comment]
Ich verliere leider die Übersicht. Könnte der Pull Request in kleinere Requests aufgeteilt werden? Mein Vorschlag: eigene Pull Requests für

- Vorschläge für neue Attribute in einen eigenen Pull Request, da Attribute besonders kritisch sind.
- Änderungen am Fragenkatalog
- Französisch und Italienisch
- Conditions und Options gleichen Themas gehören zusammen, aber thematisch sollte hier aufgeteilt werden in 
    1. neue Condition embargo und zugehörige Optionen
    2. neue Condition existing_data und zugehörige Optionen
    3. neue Condition repository_extern und zugehörige Optionen
    4. neue Condition software_generated und zugehörige Optionen
    5. sonstige Vorschläge bzgl. Optionen

Commits aus Pull Request #23 sind hier wohl versehentlich noch einmal hineingeraten. Sie doppelt zu haben, schadet vielleicht nicht, erschwert aber die Übersicht. Die sollten raus, selbstverständlich nur hier in #25.

**Comment by torsten-rathmann** [comment]
As a general remark, I would be happy to have an explanatory statement, a reason for every new attribute. For eample, the question could be added in the comment tag. A good explanatory statement would also be a requirement of a funder, university or other institution, especially with a link.

**Comment by Zack-83** [comment]
Es war zu viel auf einmal. Ich zerstückele es in vier kleineren PR.

**Pull request closed without merging**
