### PR TITLE
View for Horizon Europe

### PR DESCRIPTION
**Pull request by Zack-83**
Now it should be working

### CODE REVIEW

**Comment by torsten-rathmann** [comment]
Import of view horizon-europe was successful under RDMO 1.8.1 but when I tried to use it I got an internal server error. In the log file error.log I found the following error message:

[2022-06-27 17:25:36,671] ERROR: Internal Server Error: /projects/3/views/7/
Traceback (most recent call last):
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/rdmo/projects/views/project_view.py", line 39, in get_context_data
    snapshot=context['current_snapshot'])
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/rdmo/views/models.py", line 162, in render
    'pandoc_version': get_pandoc_main_version()
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/rdmo/views/templatetags/view_tags.py", line 148, in render_set_value
    context['value'] = get_set_value(context, set, attribute, set_prefix=set_prefix, index=index, project=project)
  File "/srv/rdmo/rdmo-app/env/lib/python3.7/site-packages/rdmo/views/templatetags/view_tags.py", line 89, in get_set_value
    set_index = set.get('set_index')
AttributeError: 'str' object has no attribute 'get'

**Comment by MyPyDavid** [comment]
Simple fix for this 
> AttributeError: 'str' object has no attribute 'get'

The for loop `{% for dataset in datasets %}` was missing in "Q06".

```python
{% for dataset in datasets %}
<p> The data might be useful to: {% render_set_value dataset 'project/dataset/reuse_scenario' %}</p>
 {% endfor %}
```

Another bug I found at "Q37", if no `value.project.costs` were given.
Fix with an extra `{% if value.project %}` for example:
```py
{% if value.project %}
<p>Costs: {{ value.project.costs.preservation.personnel|add:value.costs.preservation.non_personnel }}  
<span style="color:purple;">ODER:</span> see <a ref="#Q34">Question 34</a>.<br />  
Potential value: see <a href="#Q06">Question 6</a>.
</p>
{% else %}
<p>Costs: None
</p>
{% endif %}
```

After these two fixes I could open the view!

**Comment by Zack-83** [comment]
Ich habe es gebessert. @MyPyDavid ich kann dich leider ins Projekt nicht hinzufügen

**Comment by torsten-rathmann** [comment]
Now I can see the output of the view. With help of the attached test project I found some issues:

Action title: Not the content of https://rdmorganiser.github.io/terms/domain/project/title is inserted here but the content of the title field of the "project information".


DATA SUMMARY

Question 1: The reason for creating and not re-using are not printed.

Question 2: The description of the first dataset is inserted as description for every dataset. Data format information is missing.

Question 4: Size information is missing.

Question 5: The content for the first dataset is printed for every dataset.

Question 6: Missing "The data might be useful to: Stakeholders from industry / economy:"


FAIR DATA

Question 7: "Handle/DOI" only printed for the first dataset (This is of minor importance.)

Question 8: 
  - Can empty text boxes been leaved out?
  - The additionally printed text "The metadata created for all of the project's datasets fulfil the Grant Agreement’s requirement for a minimum set of metadata about: the datasets (description, date of deposit, author(s), venue and embargo); the European Partnership on Metrology funding; the project acronym and number; licensing terms; persistent identifiers for the dataset, the authors involved, and, if possible, their organisations and the project. Where applicable, the metadata will include persistent identifiers for related publications and other research outputs." should better be positioned in a help text.

Question 10: The additionally printed text "Yes, the chosen repository complies with the FAIR data principles (https://about.zenodo.org/principles/). The metadata are indexed in a searchable resource. Metadata are licensed under CC0, except for email addresses. All metadata are exported via OAI PMH and can be harvested." should better be positioned in a help text.

Question 11: 
  - Wrongly processed information for example dataset "Informed consents". This dataset shall not be made accessible.
  - Assingment of the text blocks to the datasets eccentric.

Question 12: Answer missing (also in the usual output without using a view)

Question 13: Printed text "the chosen repository assigned an identifier (DOI) to each of the project’s deposited datasets." is not useful here because a specific answer is given for each dataset. It is even wrong for example dataset "Informed consents", which remains closed.

Question 14: For what purpose is the additionally printed text 
"All data needed to validate the results presented in scientific publications will be made openly available as the default unless there is a specific reason not to publish the data.
Datasets which cannot be shared – voluntary restrictions
Other data may be made available on a case-by-case basis if they are relevant for third parties.
The following data will not be made publicly available: • Data obtained with the permission of third parties, but where the third parties have not agreed to make the data publicly available. • Data that disclose the identity of a manufacturer. • Data that compromise the protection of a partner's intellectual property. The level of data made available will also be considered, for example, pre-processed data will not be provided unless there is a clear reason for doing so. Datasets which cannot be shared - legal / contractual reasons
All of the data from the project will be made available, with the exception of market or customer survey data, which are commercially sensitive and cannot be shared."?

Question 15: Wrong processing, ignored "Achievement of intellectual property rights such as: patent"

Question 17: Double colon, e.g. "Dataset Patient records:: Since it cannot be excluded that future image recognition techniques make it possible to identify persons using the X-ray images, all patient data are only accessible after signing a contract that privacy will be respected."

Question 20: This question contains two parts and the answers for the two parts are mixed, e.g.
"Dataset Patient records: Yes
Yes, a summary of the access conditions and a contact will be provided in the metadata."

Question 21: This question also contains two parts and the answers for the two parts are mixed

Question 22: Wrong attribute

Question 24: This question also contains two parts. May the answers for the two parts be mixed?

Question 26: Double colon

Question 27: Link "Section 2.2" aims to a non-existing address. The answer "Yes" in the example also causes an output difficult to understand: "Yes. See Section 2.2 for further details." We need further text which part of the question is answered in Section 2.2.

Question 29: Double colon

Question 30: Double colon


OTHER RESEARCH OUTPUTS

Questions 32 and 33: An optionset is not sufficient here, we need a text field. Additionally, it should be mentioned in the text that the two questions are answered together.


ALLOCATION OF RESOURCES

Question 34: "€" and "person-months" are dispensible. Additionally, the output of "{% render_value 'project/costs/preservation/non_personnel' €.br />" is a hint that ther is a mistake in formatting the preservation costs.

Question 35: Hint "Note that costs related to research data/output management are eligible as part of the Horizon Europe grant (if compliant with the Grant Agreement conditions)." may be misinterpreted as answer.

Question 36: Empty list items; instead the answers are isolated, see example output.

Question 37: Empty list item in the example output. Double colon


DATA SECURITY

Question 38: Blank missing in question text: "security(including", answer is missing.

Question 39: Here, the repositories are inserted. In the mapping table this isn't intended.


ETHICS:

Question 40: 
  - Logical ist printed as 0/1. 
  - Most answers are leaved out.

Question 41: Logical ist printed as 0/1. Empty list item

Question 42: 
  - List item with fixed t
[Medtest.xml.txt](https://github.com/rdmorganiser/rdmo-catalog/files/9113908/Medtest.xml.txt)
ext "The European laws about data security and protection of privacy (e.g. GDPR)." doesn't match the question "Do you, or will you, make use of other national/funder/sectorial/departmental procedures for data management?"
  - Answers concerning rules of the partner institutions and other RDM regulations are leaved out
[Medtest.pdf](https://github.com/rdmorganiser/rdmo-catalog/files/9113923/Medtest.pdf)
.

**Pull request merged**
